INSERT INTO TAB_DEPARTMENT(NAME) VALUES ('Gestão');
INSERT INTO TAB_DEPARTMENT(NAME) VALUES ('Informática');

INSERT INTO TAB_USER(DEPARTMENT_ID, NAME, EMAIL) VALUES (1, 'Maria', 'maria@gmail.com');
INSERT INTO TAB_USER(DEPARTMENT_ID, NAME, EMAIL) VALUES (1, 'Bob', 'bob@gmail.com');
INSERT INTO TAB_USER(DEPARTMENT_ID, NAME, EMAIL) VALUES (2, 'Alex', 'alex@gmail.com');
INSERT INTO TAB_USER(DEPARTMENT_ID, NAME, EMAIL) VALUES (2, 'Ana', 'ana@gmail.com');